// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: edge-based-graph.proto

#include "edge-based-graph.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

extern PROTOBUF_INTERNAL_EXPORT_edge_2dbased_2dgraph_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_EdgeBasedNode_edge_2dbased_2dgraph_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_edge_2dbased_2dgraph_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_NodeBasedAnnotation_edge_2dbased_2dgraph_2eproto;
namespace pbebg {
class EdgeBasedNodeDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<EdgeBasedNode> _instance;
} _EdgeBasedNode_default_instance_;
class NodeBasedAnnotationDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<NodeBasedAnnotation> _instance;
} _NodeBasedAnnotation_default_instance_;
class EdgeBasedNodeContainerDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<EdgeBasedNodeContainer> _instance;
} _EdgeBasedNodeContainer_default_instance_;
class TurnInstructionsDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<TurnInstructions> _instance;
} _TurnInstructions_default_instance_;
class TurnPenaltiesDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<TurnPenalties> _instance;
} _TurnPenalties_default_instance_;
}  // namespace pbebg
static void InitDefaultsEdgeBasedNode_edge_2dbased_2dgraph_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::pbebg::_EdgeBasedNode_default_instance_;
    new (ptr) ::pbebg::EdgeBasedNode();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::pbebg::EdgeBasedNode::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_EdgeBasedNode_edge_2dbased_2dgraph_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsEdgeBasedNode_edge_2dbased_2dgraph_2eproto}, {}};

static void InitDefaultsNodeBasedAnnotation_edge_2dbased_2dgraph_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::pbebg::_NodeBasedAnnotation_default_instance_;
    new (ptr) ::pbebg::NodeBasedAnnotation();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::pbebg::NodeBasedAnnotation::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_NodeBasedAnnotation_edge_2dbased_2dgraph_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsNodeBasedAnnotation_edge_2dbased_2dgraph_2eproto}, {}};

static void InitDefaultsEdgeBasedNodeContainer_edge_2dbased_2dgraph_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::pbebg::_EdgeBasedNodeContainer_default_instance_;
    new (ptr) ::pbebg::EdgeBasedNodeContainer();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::pbebg::EdgeBasedNodeContainer::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_EdgeBasedNodeContainer_edge_2dbased_2dgraph_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsEdgeBasedNodeContainer_edge_2dbased_2dgraph_2eproto}, {
      &scc_info_EdgeBasedNode_edge_2dbased_2dgraph_2eproto.base,
      &scc_info_NodeBasedAnnotation_edge_2dbased_2dgraph_2eproto.base,}};

static void InitDefaultsTurnInstructions_edge_2dbased_2dgraph_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::pbebg::_TurnInstructions_default_instance_;
    new (ptr) ::pbebg::TurnInstructions();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::pbebg::TurnInstructions::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_TurnInstructions_edge_2dbased_2dgraph_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsTurnInstructions_edge_2dbased_2dgraph_2eproto}, {}};

static void InitDefaultsTurnPenalties_edge_2dbased_2dgraph_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::pbebg::_TurnPenalties_default_instance_;
    new (ptr) ::pbebg::TurnPenalties();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::pbebg::TurnPenalties::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_TurnPenalties_edge_2dbased_2dgraph_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsTurnPenalties_edge_2dbased_2dgraph_2eproto}, {}};

void InitDefaults_edge_2dbased_2dgraph_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_EdgeBasedNode_edge_2dbased_2dgraph_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_NodeBasedAnnotation_edge_2dbased_2dgraph_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_EdgeBasedNodeContainer_edge_2dbased_2dgraph_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_TurnInstructions_edge_2dbased_2dgraph_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_TurnPenalties_edge_2dbased_2dgraph_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_edge_2dbased_2dgraph_2eproto[5];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_edge_2dbased_2dgraph_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_edge_2dbased_2dgraph_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_edge_2dbased_2dgraph_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::pbebg::EdgeBasedNode, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::pbebg::EdgeBasedNode, geometry_id_),
  PROTOBUF_FIELD_OFFSET(::pbebg::EdgeBasedNode, component_id_),
  PROTOBUF_FIELD_OFFSET(::pbebg::EdgeBasedNode, annotation_id_),
  PROTOBUF_FIELD_OFFSET(::pbebg::EdgeBasedNode, is_tiny_),
  PROTOBUF_FIELD_OFFSET(::pbebg::EdgeBasedNode, segregated_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::pbebg::NodeBasedAnnotation, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::pbebg::NodeBasedAnnotation, name_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::pbebg::EdgeBasedNodeContainer, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::pbebg::EdgeBasedNodeContainer, nodes_),
  PROTOBUF_FIELD_OFFSET(::pbebg::EdgeBasedNodeContainer, annotation_data_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::pbebg::TurnInstructions, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::pbebg::TurnInstructions, turn_instruction_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::pbebg::TurnPenalties, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::pbebg::TurnPenalties, turn_penalties_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::pbebg::EdgeBasedNode)},
  { 10, -1, sizeof(::pbebg::NodeBasedAnnotation)},
  { 16, -1, sizeof(::pbebg::EdgeBasedNodeContainer)},
  { 23, -1, sizeof(::pbebg::TurnInstructions)},
  { 29, -1, sizeof(::pbebg::TurnPenalties)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::pbebg::_EdgeBasedNode_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::pbebg::_NodeBasedAnnotation_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::pbebg::_EdgeBasedNodeContainer_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::pbebg::_TurnInstructions_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::pbebg::_TurnPenalties_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_edge_2dbased_2dgraph_2eproto = {
  {}, AddDescriptors_edge_2dbased_2dgraph_2eproto, "edge-based-graph.proto", schemas,
  file_default_instances, TableStruct_edge_2dbased_2dgraph_2eproto::offsets,
  file_level_metadata_edge_2dbased_2dgraph_2eproto, 5, file_level_enum_descriptors_edge_2dbased_2dgraph_2eproto, file_level_service_descriptors_edge_2dbased_2dgraph_2eproto,
};

const char descriptor_table_protodef_edge_2dbased_2dgraph_2eproto[] =
  "\n\026edge-based-graph.proto\022\005pbebg\"v\n\rEdgeB"
  "asedNode\022\023\n\013geometry_id\030\001 \001(\r\022\024\n\014compone"
  "nt_id\030\002 \001(\r\022\025\n\rannotation_id\030\003 \001(\r\022\017\n\007is"
  "_tiny\030\004 \001(\010\022\022\n\nsegregated\030\005 \001(\010\"&\n\023NodeB"
  "asedAnnotation\022\017\n\007name_id\030\001 \001(\r\"r\n\026EdgeB"
  "asedNodeContainer\022#\n\005nodes\030\001 \003(\0132\024.pbebg"
  ".EdgeBasedNode\0223\n\017annotation_data\030\002 \003(\0132"
  "\032.pbebg.NodeBasedAnnotation\",\n\020TurnInstr"
  "uctions\022\030\n\020turn_instruction\030\001 \003(\r\"\'\n\rTur"
  "nPenalties\022\026\n\016turn_penalties\030\001 \003(\rb\006prot"
  "o3"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_edge_2dbased_2dgraph_2eproto = {
  false, InitDefaults_edge_2dbased_2dgraph_2eproto, 
  descriptor_table_protodef_edge_2dbased_2dgraph_2eproto,
  "edge-based-graph.proto", &assign_descriptors_table_edge_2dbased_2dgraph_2eproto, 402,
};

void AddDescriptors_edge_2dbased_2dgraph_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_edge_2dbased_2dgraph_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_edge_2dbased_2dgraph_2eproto = []() { AddDescriptors_edge_2dbased_2dgraph_2eproto(); return true; }();
namespace pbebg {

// ===================================================================

void EdgeBasedNode::InitAsDefaultInstance() {
}
class EdgeBasedNode::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int EdgeBasedNode::kGeometryIdFieldNumber;
const int EdgeBasedNode::kComponentIdFieldNumber;
const int EdgeBasedNode::kAnnotationIdFieldNumber;
const int EdgeBasedNode::kIsTinyFieldNumber;
const int EdgeBasedNode::kSegregatedFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

EdgeBasedNode::EdgeBasedNode()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pbebg.EdgeBasedNode)
}
EdgeBasedNode::EdgeBasedNode(const EdgeBasedNode& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&geometry_id_, &from.geometry_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&segregated_) -
    reinterpret_cast<char*>(&geometry_id_)) + sizeof(segregated_));
  // @@protoc_insertion_point(copy_constructor:pbebg.EdgeBasedNode)
}

void EdgeBasedNode::SharedCtor() {
  ::memset(&geometry_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&segregated_) -
      reinterpret_cast<char*>(&geometry_id_)) + sizeof(segregated_));
}

EdgeBasedNode::~EdgeBasedNode() {
  // @@protoc_insertion_point(destructor:pbebg.EdgeBasedNode)
  SharedDtor();
}

void EdgeBasedNode::SharedDtor() {
}

void EdgeBasedNode::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const EdgeBasedNode& EdgeBasedNode::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_EdgeBasedNode_edge_2dbased_2dgraph_2eproto.base);
  return *internal_default_instance();
}


void EdgeBasedNode::Clear() {
// @@protoc_insertion_point(message_clear_start:pbebg.EdgeBasedNode)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&geometry_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&segregated_) -
      reinterpret_cast<char*>(&geometry_id_)) + sizeof(segregated_));
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* EdgeBasedNode::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<EdgeBasedNode*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // uint32 geometry_id = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 8) goto handle_unusual;
        msg->set_geometry_id(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // uint32 component_id = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 16) goto handle_unusual;
        msg->set_component_id(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // uint32 annotation_id = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 24) goto handle_unusual;
        msg->set_annotation_id(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // bool is_tiny = 4;
      case 4: {
        if (static_cast<::google::protobuf::uint8>(tag) != 32) goto handle_unusual;
        msg->set_is_tiny(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // bool segregated = 5;
      case 5: {
        if (static_cast<::google::protobuf::uint8>(tag) != 40) goto handle_unusual;
        msg->set_segregated(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool EdgeBasedNode::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pbebg.EdgeBasedNode)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 geometry_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (8 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &geometry_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 component_id = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (16 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &component_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 annotation_id = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (24 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &annotation_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool is_tiny = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (32 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &is_tiny_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool segregated = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (40 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &segregated_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pbebg.EdgeBasedNode)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pbebg.EdgeBasedNode)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void EdgeBasedNode::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pbebg.EdgeBasedNode)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 geometry_id = 1;
  if (this->geometry_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->geometry_id(), output);
  }

  // uint32 component_id = 2;
  if (this->component_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->component_id(), output);
  }

  // uint32 annotation_id = 3;
  if (this->annotation_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->annotation_id(), output);
  }

  // bool is_tiny = 4;
  if (this->is_tiny() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(4, this->is_tiny(), output);
  }

  // bool segregated = 5;
  if (this->segregated() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(5, this->segregated(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:pbebg.EdgeBasedNode)
}

::google::protobuf::uint8* EdgeBasedNode::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:pbebg.EdgeBasedNode)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 geometry_id = 1;
  if (this->geometry_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->geometry_id(), target);
  }

  // uint32 component_id = 2;
  if (this->component_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->component_id(), target);
  }

  // uint32 annotation_id = 3;
  if (this->annotation_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->annotation_id(), target);
  }

  // bool is_tiny = 4;
  if (this->is_tiny() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(4, this->is_tiny(), target);
  }

  // bool segregated = 5;
  if (this->segregated() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(5, this->segregated(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pbebg.EdgeBasedNode)
  return target;
}

size_t EdgeBasedNode::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pbebg.EdgeBasedNode)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 geometry_id = 1;
  if (this->geometry_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->geometry_id());
  }

  // uint32 component_id = 2;
  if (this->component_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->component_id());
  }

  // uint32 annotation_id = 3;
  if (this->annotation_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->annotation_id());
  }

  // bool is_tiny = 4;
  if (this->is_tiny() != 0) {
    total_size += 1 + 1;
  }

  // bool segregated = 5;
  if (this->segregated() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void EdgeBasedNode::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pbebg.EdgeBasedNode)
  GOOGLE_DCHECK_NE(&from, this);
  const EdgeBasedNode* source =
      ::google::protobuf::DynamicCastToGenerated<EdgeBasedNode>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pbebg.EdgeBasedNode)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pbebg.EdgeBasedNode)
    MergeFrom(*source);
  }
}

void EdgeBasedNode::MergeFrom(const EdgeBasedNode& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pbebg.EdgeBasedNode)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.geometry_id() != 0) {
    set_geometry_id(from.geometry_id());
  }
  if (from.component_id() != 0) {
    set_component_id(from.component_id());
  }
  if (from.annotation_id() != 0) {
    set_annotation_id(from.annotation_id());
  }
  if (from.is_tiny() != 0) {
    set_is_tiny(from.is_tiny());
  }
  if (from.segregated() != 0) {
    set_segregated(from.segregated());
  }
}

void EdgeBasedNode::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pbebg.EdgeBasedNode)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void EdgeBasedNode::CopyFrom(const EdgeBasedNode& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pbebg.EdgeBasedNode)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EdgeBasedNode::IsInitialized() const {
  return true;
}

void EdgeBasedNode::Swap(EdgeBasedNode* other) {
  if (other == this) return;
  InternalSwap(other);
}
void EdgeBasedNode::InternalSwap(EdgeBasedNode* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(geometry_id_, other->geometry_id_);
  swap(component_id_, other->component_id_);
  swap(annotation_id_, other->annotation_id_);
  swap(is_tiny_, other->is_tiny_);
  swap(segregated_, other->segregated_);
}

::google::protobuf::Metadata EdgeBasedNode::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_edge_2dbased_2dgraph_2eproto);
  return ::file_level_metadata_edge_2dbased_2dgraph_2eproto[kIndexInFileMessages];
}


// ===================================================================

void NodeBasedAnnotation::InitAsDefaultInstance() {
}
class NodeBasedAnnotation::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int NodeBasedAnnotation::kNameIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

NodeBasedAnnotation::NodeBasedAnnotation()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pbebg.NodeBasedAnnotation)
}
NodeBasedAnnotation::NodeBasedAnnotation(const NodeBasedAnnotation& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_id_ = from.name_id_;
  // @@protoc_insertion_point(copy_constructor:pbebg.NodeBasedAnnotation)
}

void NodeBasedAnnotation::SharedCtor() {
  name_id_ = 0u;
}

NodeBasedAnnotation::~NodeBasedAnnotation() {
  // @@protoc_insertion_point(destructor:pbebg.NodeBasedAnnotation)
  SharedDtor();
}

void NodeBasedAnnotation::SharedDtor() {
}

void NodeBasedAnnotation::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const NodeBasedAnnotation& NodeBasedAnnotation::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_NodeBasedAnnotation_edge_2dbased_2dgraph_2eproto.base);
  return *internal_default_instance();
}


void NodeBasedAnnotation::Clear() {
// @@protoc_insertion_point(message_clear_start:pbebg.NodeBasedAnnotation)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_id_ = 0u;
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* NodeBasedAnnotation::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<NodeBasedAnnotation*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // uint32 name_id = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 8) goto handle_unusual;
        msg->set_name_id(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool NodeBasedAnnotation::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pbebg.NodeBasedAnnotation)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 name_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (8 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &name_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pbebg.NodeBasedAnnotation)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pbebg.NodeBasedAnnotation)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void NodeBasedAnnotation::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pbebg.NodeBasedAnnotation)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 name_id = 1;
  if (this->name_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->name_id(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:pbebg.NodeBasedAnnotation)
}

::google::protobuf::uint8* NodeBasedAnnotation::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:pbebg.NodeBasedAnnotation)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 name_id = 1;
  if (this->name_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->name_id(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pbebg.NodeBasedAnnotation)
  return target;
}

size_t NodeBasedAnnotation::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pbebg.NodeBasedAnnotation)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 name_id = 1;
  if (this->name_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->name_id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void NodeBasedAnnotation::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pbebg.NodeBasedAnnotation)
  GOOGLE_DCHECK_NE(&from, this);
  const NodeBasedAnnotation* source =
      ::google::protobuf::DynamicCastToGenerated<NodeBasedAnnotation>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pbebg.NodeBasedAnnotation)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pbebg.NodeBasedAnnotation)
    MergeFrom(*source);
  }
}

void NodeBasedAnnotation::MergeFrom(const NodeBasedAnnotation& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pbebg.NodeBasedAnnotation)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.name_id() != 0) {
    set_name_id(from.name_id());
  }
}

void NodeBasedAnnotation::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pbebg.NodeBasedAnnotation)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NodeBasedAnnotation::CopyFrom(const NodeBasedAnnotation& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pbebg.NodeBasedAnnotation)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NodeBasedAnnotation::IsInitialized() const {
  return true;
}

void NodeBasedAnnotation::Swap(NodeBasedAnnotation* other) {
  if (other == this) return;
  InternalSwap(other);
}
void NodeBasedAnnotation::InternalSwap(NodeBasedAnnotation* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(name_id_, other->name_id_);
}

::google::protobuf::Metadata NodeBasedAnnotation::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_edge_2dbased_2dgraph_2eproto);
  return ::file_level_metadata_edge_2dbased_2dgraph_2eproto[kIndexInFileMessages];
}


// ===================================================================

void EdgeBasedNodeContainer::InitAsDefaultInstance() {
}
class EdgeBasedNodeContainer::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int EdgeBasedNodeContainer::kNodesFieldNumber;
const int EdgeBasedNodeContainer::kAnnotationDataFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

EdgeBasedNodeContainer::EdgeBasedNodeContainer()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pbebg.EdgeBasedNodeContainer)
}
EdgeBasedNodeContainer::EdgeBasedNodeContainer(const EdgeBasedNodeContainer& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      nodes_(from.nodes_),
      annotation_data_(from.annotation_data_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:pbebg.EdgeBasedNodeContainer)
}

void EdgeBasedNodeContainer::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_EdgeBasedNodeContainer_edge_2dbased_2dgraph_2eproto.base);
}

EdgeBasedNodeContainer::~EdgeBasedNodeContainer() {
  // @@protoc_insertion_point(destructor:pbebg.EdgeBasedNodeContainer)
  SharedDtor();
}

void EdgeBasedNodeContainer::SharedDtor() {
}

void EdgeBasedNodeContainer::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const EdgeBasedNodeContainer& EdgeBasedNodeContainer::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_EdgeBasedNodeContainer_edge_2dbased_2dgraph_2eproto.base);
  return *internal_default_instance();
}


void EdgeBasedNodeContainer::Clear() {
// @@protoc_insertion_point(message_clear_start:pbebg.EdgeBasedNodeContainer)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  nodes_.Clear();
  annotation_data_.Clear();
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* EdgeBasedNodeContainer::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<EdgeBasedNodeContainer*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // repeated .pbebg.EdgeBasedNode nodes = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        do {
          ptr = ::google::protobuf::io::ReadSize(ptr, &size);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          parser_till_end = ::pbebg::EdgeBasedNode::_InternalParse;
          object = msg->add_nodes();
          if (size > end - ptr) goto len_delim_till_end;
          ptr += size;
          GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
              {parser_till_end, object}, ptr - size, ptr));
          if (ptr >= end) break;
        } while ((::google::protobuf::io::UnalignedLoad<::google::protobuf::uint64>(ptr) & 255) == 10 && (ptr += 1));
        break;
      }
      // repeated .pbebg.NodeBasedAnnotation annotation_data = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 18) goto handle_unusual;
        do {
          ptr = ::google::protobuf::io::ReadSize(ptr, &size);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          parser_till_end = ::pbebg::NodeBasedAnnotation::_InternalParse;
          object = msg->add_annotation_data();
          if (size > end - ptr) goto len_delim_till_end;
          ptr += size;
          GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
              {parser_till_end, object}, ptr - size, ptr));
          if (ptr >= end) break;
        } while ((::google::protobuf::io::UnalignedLoad<::google::protobuf::uint64>(ptr) & 255) == 18 && (ptr += 1));
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool EdgeBasedNodeContainer::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pbebg.EdgeBasedNodeContainer)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .pbebg.EdgeBasedNode nodes = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_nodes()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .pbebg.NodeBasedAnnotation annotation_data = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (18 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_annotation_data()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pbebg.EdgeBasedNodeContainer)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pbebg.EdgeBasedNodeContainer)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void EdgeBasedNodeContainer::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pbebg.EdgeBasedNodeContainer)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .pbebg.EdgeBasedNode nodes = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->nodes_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->nodes(static_cast<int>(i)),
      output);
  }

  // repeated .pbebg.NodeBasedAnnotation annotation_data = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->annotation_data_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2,
      this->annotation_data(static_cast<int>(i)),
      output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:pbebg.EdgeBasedNodeContainer)
}

::google::protobuf::uint8* EdgeBasedNodeContainer::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:pbebg.EdgeBasedNodeContainer)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .pbebg.EdgeBasedNode nodes = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->nodes_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->nodes(static_cast<int>(i)), target);
  }

  // repeated .pbebg.NodeBasedAnnotation annotation_data = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->annotation_data_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->annotation_data(static_cast<int>(i)), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pbebg.EdgeBasedNodeContainer)
  return target;
}

size_t EdgeBasedNodeContainer::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pbebg.EdgeBasedNodeContainer)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .pbebg.EdgeBasedNode nodes = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->nodes_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->nodes(static_cast<int>(i)));
    }
  }

  // repeated .pbebg.NodeBasedAnnotation annotation_data = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->annotation_data_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->annotation_data(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void EdgeBasedNodeContainer::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pbebg.EdgeBasedNodeContainer)
  GOOGLE_DCHECK_NE(&from, this);
  const EdgeBasedNodeContainer* source =
      ::google::protobuf::DynamicCastToGenerated<EdgeBasedNodeContainer>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pbebg.EdgeBasedNodeContainer)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pbebg.EdgeBasedNodeContainer)
    MergeFrom(*source);
  }
}

void EdgeBasedNodeContainer::MergeFrom(const EdgeBasedNodeContainer& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pbebg.EdgeBasedNodeContainer)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  nodes_.MergeFrom(from.nodes_);
  annotation_data_.MergeFrom(from.annotation_data_);
}

void EdgeBasedNodeContainer::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pbebg.EdgeBasedNodeContainer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void EdgeBasedNodeContainer::CopyFrom(const EdgeBasedNodeContainer& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pbebg.EdgeBasedNodeContainer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EdgeBasedNodeContainer::IsInitialized() const {
  return true;
}

void EdgeBasedNodeContainer::Swap(EdgeBasedNodeContainer* other) {
  if (other == this) return;
  InternalSwap(other);
}
void EdgeBasedNodeContainer::InternalSwap(EdgeBasedNodeContainer* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  CastToBase(&nodes_)->InternalSwap(CastToBase(&other->nodes_));
  CastToBase(&annotation_data_)->InternalSwap(CastToBase(&other->annotation_data_));
}

::google::protobuf::Metadata EdgeBasedNodeContainer::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_edge_2dbased_2dgraph_2eproto);
  return ::file_level_metadata_edge_2dbased_2dgraph_2eproto[kIndexInFileMessages];
}


// ===================================================================

void TurnInstructions::InitAsDefaultInstance() {
}
class TurnInstructions::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TurnInstructions::kTurnInstructionFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TurnInstructions::TurnInstructions()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pbebg.TurnInstructions)
}
TurnInstructions::TurnInstructions(const TurnInstructions& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      turn_instruction_(from.turn_instruction_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:pbebg.TurnInstructions)
}

void TurnInstructions::SharedCtor() {
}

TurnInstructions::~TurnInstructions() {
  // @@protoc_insertion_point(destructor:pbebg.TurnInstructions)
  SharedDtor();
}

void TurnInstructions::SharedDtor() {
}

void TurnInstructions::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const TurnInstructions& TurnInstructions::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_TurnInstructions_edge_2dbased_2dgraph_2eproto.base);
  return *internal_default_instance();
}


void TurnInstructions::Clear() {
// @@protoc_insertion_point(message_clear_start:pbebg.TurnInstructions)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  turn_instruction_.Clear();
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* TurnInstructions::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<TurnInstructions*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // repeated uint32 turn_instruction = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) == 10) {
          ptr = ::google::protobuf::io::ReadSize(ptr, &size);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          parser_till_end = ::google::protobuf::internal::PackedUInt32Parser;
          object = msg->mutable_turn_instruction();
          if (size > end - ptr) goto len_delim_till_end;
          auto newend = ptr + size;
          if (size) ptr = parser_till_end(ptr, newend, object, ctx);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr == newend);
          break;
        } else if (static_cast<::google::protobuf::uint8>(tag) != 8) goto handle_unusual;
        do {
          msg->add_turn_instruction(::google::protobuf::internal::ReadVarint(&ptr));
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          if (ptr >= end) break;
        } while ((::google::protobuf::io::UnalignedLoad<::google::protobuf::uint64>(ptr) & 255) == 8 && (ptr += 1));
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool TurnInstructions::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pbebg.TurnInstructions)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated uint32 turn_instruction = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, this->mutable_turn_instruction())));
        } else if (static_cast< ::google::protobuf::uint8>(tag) == (8 & 0xFF)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 1, 10u, input, this->mutable_turn_instruction())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pbebg.TurnInstructions)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pbebg.TurnInstructions)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void TurnInstructions::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pbebg.TurnInstructions)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated uint32 turn_instruction = 1;
  if (this->turn_instruction_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(1, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_turn_instruction_cached_byte_size_.load(
        std::memory_order_relaxed));
  }
  for (int i = 0, n = this->turn_instruction_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32NoTag(
      this->turn_instruction(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:pbebg.TurnInstructions)
}

::google::protobuf::uint8* TurnInstructions::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:pbebg.TurnInstructions)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated uint32 turn_instruction = 1;
  if (this->turn_instruction_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      1,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        _turn_instruction_cached_byte_size_.load(std::memory_order_relaxed),
         target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt32NoTagToArray(this->turn_instruction_, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pbebg.TurnInstructions)
  return target;
}

size_t TurnInstructions::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pbebg.TurnInstructions)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated uint32 turn_instruction = 1;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      UInt32Size(this->turn_instruction_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast<::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    _turn_instruction_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void TurnInstructions::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pbebg.TurnInstructions)
  GOOGLE_DCHECK_NE(&from, this);
  const TurnInstructions* source =
      ::google::protobuf::DynamicCastToGenerated<TurnInstructions>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pbebg.TurnInstructions)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pbebg.TurnInstructions)
    MergeFrom(*source);
  }
}

void TurnInstructions::MergeFrom(const TurnInstructions& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pbebg.TurnInstructions)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  turn_instruction_.MergeFrom(from.turn_instruction_);
}

void TurnInstructions::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pbebg.TurnInstructions)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TurnInstructions::CopyFrom(const TurnInstructions& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pbebg.TurnInstructions)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TurnInstructions::IsInitialized() const {
  return true;
}

void TurnInstructions::Swap(TurnInstructions* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TurnInstructions::InternalSwap(TurnInstructions* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  turn_instruction_.InternalSwap(&other->turn_instruction_);
}

::google::protobuf::Metadata TurnInstructions::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_edge_2dbased_2dgraph_2eproto);
  return ::file_level_metadata_edge_2dbased_2dgraph_2eproto[kIndexInFileMessages];
}


// ===================================================================

void TurnPenalties::InitAsDefaultInstance() {
}
class TurnPenalties::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int TurnPenalties::kTurnPenaltiesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

TurnPenalties::TurnPenalties()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pbebg.TurnPenalties)
}
TurnPenalties::TurnPenalties(const TurnPenalties& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      turn_penalties_(from.turn_penalties_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:pbebg.TurnPenalties)
}

void TurnPenalties::SharedCtor() {
}

TurnPenalties::~TurnPenalties() {
  // @@protoc_insertion_point(destructor:pbebg.TurnPenalties)
  SharedDtor();
}

void TurnPenalties::SharedDtor() {
}

void TurnPenalties::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const TurnPenalties& TurnPenalties::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_TurnPenalties_edge_2dbased_2dgraph_2eproto.base);
  return *internal_default_instance();
}


void TurnPenalties::Clear() {
// @@protoc_insertion_point(message_clear_start:pbebg.TurnPenalties)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  turn_penalties_.Clear();
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* TurnPenalties::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<TurnPenalties*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // repeated uint32 turn_penalties = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) == 10) {
          ptr = ::google::protobuf::io::ReadSize(ptr, &size);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          parser_till_end = ::google::protobuf::internal::PackedUInt32Parser;
          object = msg->mutable_turn_penalties();
          if (size > end - ptr) goto len_delim_till_end;
          auto newend = ptr + size;
          if (size) ptr = parser_till_end(ptr, newend, object, ctx);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr == newend);
          break;
        } else if (static_cast<::google::protobuf::uint8>(tag) != 8) goto handle_unusual;
        do {
          msg->add_turn_penalties(::google::protobuf::internal::ReadVarint(&ptr));
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          if (ptr >= end) break;
        } while ((::google::protobuf::io::UnalignedLoad<::google::protobuf::uint64>(ptr) & 255) == 8 && (ptr += 1));
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool TurnPenalties::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pbebg.TurnPenalties)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated uint32 turn_penalties = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, this->mutable_turn_penalties())));
        } else if (static_cast< ::google::protobuf::uint8>(tag) == (8 & 0xFF)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 1, 10u, input, this->mutable_turn_penalties())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pbebg.TurnPenalties)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pbebg.TurnPenalties)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void TurnPenalties::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pbebg.TurnPenalties)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated uint32 turn_penalties = 1;
  if (this->turn_penalties_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(1, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_turn_penalties_cached_byte_size_.load(
        std::memory_order_relaxed));
  }
  for (int i = 0, n = this->turn_penalties_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32NoTag(
      this->turn_penalties(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:pbebg.TurnPenalties)
}

::google::protobuf::uint8* TurnPenalties::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:pbebg.TurnPenalties)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated uint32 turn_penalties = 1;
  if (this->turn_penalties_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      1,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        _turn_penalties_cached_byte_size_.load(std::memory_order_relaxed),
         target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt32NoTagToArray(this->turn_penalties_, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pbebg.TurnPenalties)
  return target;
}

size_t TurnPenalties::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pbebg.TurnPenalties)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated uint32 turn_penalties = 1;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      UInt32Size(this->turn_penalties_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast<::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    _turn_penalties_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void TurnPenalties::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pbebg.TurnPenalties)
  GOOGLE_DCHECK_NE(&from, this);
  const TurnPenalties* source =
      ::google::protobuf::DynamicCastToGenerated<TurnPenalties>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pbebg.TurnPenalties)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pbebg.TurnPenalties)
    MergeFrom(*source);
  }
}

void TurnPenalties::MergeFrom(const TurnPenalties& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pbebg.TurnPenalties)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  turn_penalties_.MergeFrom(from.turn_penalties_);
}

void TurnPenalties::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pbebg.TurnPenalties)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TurnPenalties::CopyFrom(const TurnPenalties& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pbebg.TurnPenalties)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TurnPenalties::IsInitialized() const {
  return true;
}

void TurnPenalties::Swap(TurnPenalties* other) {
  if (other == this) return;
  InternalSwap(other);
}
void TurnPenalties::InternalSwap(TurnPenalties* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  turn_penalties_.InternalSwap(&other->turn_penalties_);
}

::google::protobuf::Metadata TurnPenalties::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_edge_2dbased_2dgraph_2eproto);
  return ::file_level_metadata_edge_2dbased_2dgraph_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace pbebg
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::pbebg::EdgeBasedNode* Arena::CreateMaybeMessage< ::pbebg::EdgeBasedNode >(Arena* arena) {
  return Arena::CreateInternal< ::pbebg::EdgeBasedNode >(arena);
}
template<> PROTOBUF_NOINLINE ::pbebg::NodeBasedAnnotation* Arena::CreateMaybeMessage< ::pbebg::NodeBasedAnnotation >(Arena* arena) {
  return Arena::CreateInternal< ::pbebg::NodeBasedAnnotation >(arena);
}
template<> PROTOBUF_NOINLINE ::pbebg::EdgeBasedNodeContainer* Arena::CreateMaybeMessage< ::pbebg::EdgeBasedNodeContainer >(Arena* arena) {
  return Arena::CreateInternal< ::pbebg::EdgeBasedNodeContainer >(arena);
}
template<> PROTOBUF_NOINLINE ::pbebg::TurnInstructions* Arena::CreateMaybeMessage< ::pbebg::TurnInstructions >(Arena* arena) {
  return Arena::CreateInternal< ::pbebg::TurnInstructions >(arena);
}
template<> PROTOBUF_NOINLINE ::pbebg::TurnPenalties* Arena::CreateMaybeMessage< ::pbebg::TurnPenalties >(Arena* arena) {
  return Arena::CreateInternal< ::pbebg::TurnPenalties >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
